// <auto-generated />
using System;
using HairSalon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HairSalon.Migrations
{
    [DbContext(typeof(HairSalonContext))]
    [Migration("20260516223145_updateSeeder3")]
    partial class updateSeeder3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HairSalon.Models.Master", b =>
                {
                    b.Property<int>("MasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("Описание");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Адрес почты");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Опыт");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Имя");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Пол");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Фамилия");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Роль");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MasterId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Masters_Email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Masters");

                    b.HasData(
                        new
                        {
                            MasterId = 1,
                            Description = "по умолчанию 1",
                            Email = "YGGDRASIL@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Сатору",
                            Gender = "М",
                            LastName = "Судзуки",
                            Role = "Master",
                            UserId = 1
                        },
                        new
                        {
                            MasterId = 2,
                            Description = "по умолчанию 2",
                            Email = "Overlord@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Айнз",
                            Gender = "М",
                            LastName = "ОалГоун",
                            Role = "Master",
                            UserId = 2
                        },
                        new
                        {
                            MasterId = 3,
                            Description = "по умолчанию 3",
                            Email = "Degurechaff@gmail.com",
                            Experience = "100 Лет",
                            FirstName = "Таня",
                            Gender = "Ж",
                            LastName = "Дёгурешафф",
                            Role = "Master",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("HairSalon.Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("MasterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("Время записи");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("MasterId", "Time")
                        .IsUnique()
                        .HasDatabaseName("IX_Receptions_MasterId_Time");

                    b.ToTable("Receptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasterId = 1,
                            ServiceId = 1,
                            Time = new DateTime(2138, 12, 1, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            MasterId = 2,
                            ServiceId = 2,
                            Time = new DateTime(2138, 12, 2, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            MasterId = 3,
                            ServiceId = 3,
                            Time = new DateTime(2138, 12, 3, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HairSalon.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasColumnName("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Название");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Цена");

                    b.HasKey("ServiceId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Services_Name");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "по умолчанию 1",
                            Name = "Стрижка",
                            Price = 1000m
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "по умолчанию 2",
                            Name = "Окрашивание",
                            Price = 2000m
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "по умолчанию 3",
                            Name = "Восстановление",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("HairSalon.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Активен");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Логин");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Пароль");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Роль");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Имя пользователя");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Login");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "YGGDRASIL@gmail.com",
                            IsActive = true,
                            Login = "Satoru",
                            PasswordHash = "hash1",
                            Role = "Master",
                            Username = "Momonga"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Overlord@gmail.com",
                            IsActive = true,
                            Login = "Sorcerer King",
                            PasswordHash = "hash2",
                            Role = "Master",
                            Username = "Ainz Ooal Gown"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Degurechaff@gmail.com",
                            IsActive = true,
                            Login = "Tanya",
                            PasswordHash = "hash3",
                            Role = "Master",
                            Username = "Gun"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "albedo@gmail.com",
                            IsActive = true,
                            Login = "albedo",
                            PasswordHash = "hash4",
                            Role = "User",
                            Username = "LvAnz"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "Garuganchua@gmail.com",
                            IsActive = true,
                            Login = "Garuganchua",
                            PasswordHash = "hash5",
                            Role = "User",
                            Username = "Garuganchua"
                        });
                });

            modelBuilder.Entity("HairSalon.Models.Master", b =>
                {
                    b.HasOne("HairSalon.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("HairSalon.Models.Master", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HairSalon.Models.Reception", b =>
                {
                    b.HasOne("HairSalon.Models.User", "Client")
                        .WithMany("Receptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HairSalon.Models.Master", "Master")
                        .WithMany("Receptions")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HairSalon.Models.Service", "Service")
                        .WithMany("Receptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Master");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HairSalon.Models.Master", b =>
                {
                    b.Navigation("Receptions");
                });

            modelBuilder.Entity("HairSalon.Models.Service", b =>
                {
                    b.Navigation("Receptions");
                });

            modelBuilder.Entity("HairSalon.Models.User", b =>
                {
                    b.Navigation("Receptions");
                });
#pragma warning restore 612, 618
        }
    }
}
